# Made by Java20 - Nguyễn Anh Tú
# Quest: Mapping entity cho project OsahanEat

spring:
  datasource:
    url: jdbc:mysql://localhost:3302/osahan_db
    username: root
    password: 1312
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
